### ISSUE TITLE
discrepancies in my_collect_spec.rb

### ISSUE THREAD

**Issue by iamnotsosure** [learn-co-curriculum/my-collect#14]
I came across a few discrepancies in the spec file that was cloned when i clicked the open button in this exercise. I was given the following spec file: 

```
describe "my_collect" do
  let(:languages) { ['ruby', 'javascript', 'python', 'objective-c'] }
  let(:students) { ['Tim Jones', 'Tom Smith', 'Sophie Johnson', 'Antoin Miller'] }

  it "can handle an empty collection" do
    empty_array = []
    counter = 0
      my_collect(empty_array) do |x|
        counter += 1
      end
    expect(counter).to eq(0)
  end

  it "yields the correct element from a given collection, in this case languages" do
    my_collect(languages) do |language|
      expect(language).to_not eq(nil)
    end
  end

  it "returns a new collection of appropriately modified elements, in this case capitalized languages" do
    expect(my_collect(languages) do |language|
      language.upcase
    end).to eq(["RUBY", "JAVASCRIPT", "PYTHON", "OBJECTIVE-C"])
  end

  it 'does not modify the original collection' do
    my_collect(languages) do |language|
      language.upcase
    end
    expect(languages).to eq(['ruby', 'javascript', 'python', 'objective-c'])
  end

  it "yields the correct element from the given collection, in this case students" do
    my_collect(students) do |student|
      expect(student).to_not eq(nil)
    end
  end

  it "returns a new collection of appropriately modified elements, in this case student first names" do
    expect(my_collect(students) do |language|
      student.split(" ").first
    end).to eq(["Tim", "Tom", "Sophie", "Antoin"])
  end

  it 'does not modify the original collection' do
    my_collect(students) do |language|
      language.upcase
    end
    expect(students).to eq(['Tim Jones', 'Tom Smith', 'Sophie Johnson', 'Antoin Miller'])
  end
end
```

The [solution](https://github.com/learn-co-students/my-collect-001-prework-web/blob/solution/spec/my_collect_spec.rb/ "solution") provided in this exercise's tree does not line up with the spec file that the learn button gave to me.

I also came across an unused variable in the second `my_collect(students)` block: 
```
it "returns a new collection of appropriately modified elements, in this case student first names" do
    expect(my_collect(students) do |language|
      student.split(" ").first
    end).to eq(["Tim", "Tom", "Sophie", "Antoin"])
  end
```
This block initially didn't allow my code to pass. I went ahead and changed `|language|` to `|student|` on my end which allowed `student.split(" ").first` to pass.

I'm not sure if this was intentional, but it helped me understand spec files more!

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by ga-be** [comment]
Fixed: https://github.com/learn-co-curriculum/my-collect/pull/17
