### ISSUE TITLE
Error in test file

### ISSUE THREAD

**Issue by citurbe** [learn-co-curriculum/my-collect#19]
Looks like there's an error in the test file that's causing it to fail even when the method is written correctly. Lines 39 - 43 in my_collect_spec.rb are:

  it "returns a new collection of appropriately modified elements, in this case student first names" do
    expect(my_collect(students) do |language|
      student.split(" ").first
    end).to eq(["Tim", "Tom", "Sophie", "Antoin"])
  end

Instead of |language| it should be |student| - I made this change and the test passed

**Comment by gj** [comment]
Fixed in #17. Thanks @citurbe !
