### ISSUE TITLE
won't return new arrays, only originals

### ISSUE THREAD

**Issue by Shadow073180** [learn-co-curriculum/my-collect#29]
`keeps returning the original array

def my_collect(array)
  i = 0 
 
  while i < array.length 
   yield (array[i])
   i = i + 1 
  end
return array
end

names = ["Tim Jones", "Tom Smith", "Jim Campagno"]
  my_collect(names) do |x|
   x.split(" ").first
 
end

collection = ["ruby", "javascript", "python", "objective-c"]
  my_collect(collection) do |lang|
    lang.upcase

end`

**Comment by jenmyers** [comment]
Hello!

It looks like this isn't a bug in the curriculum, but a misunderstanding you have with the material. That's no problem though! Go ahead and hit the Ask A Question button on learn.co. Either a community member or a technical coach will be able to help you understand this stuff.

Good luck!
