### ISSUE TITLE
Consider changing starter code in lib/my_collect.rb

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/my-collect#30]
Change:
def my collect()

to:

def my_collect
end

#this way it will not throw a syntax error right away and confuse students.

**Comment by drakeltheryuujin** [comment]
Hi @justinddaniel,

There isn't currently starter code in `lib/my_collect.rb`. I also do not see this in the README nor spec files. I cannot reproduce this issue. If you think that it's not fixed, feel free to reopen this issue and we'll take another look. Thakns for contributing! 💙
