### ISSUE TITLE
my-collect lab

### ISSUE THREAD

**Issue by CRichards97** [learn-co-curriculum/my-collect#35]
I seem to be having an issue submitting my lab. I just need help figuring out how to solve this. 
Thanks!

**Comment by lizbur10** [comment]
Hi there,

I'm sorry to hear that you're having problems submitting your lab. Note, however, that submitting issues on GitHub is the way to report errors or problems with the lab itself (curriculum issues). If you still need help submitting the lab, please reach out to your instructors or to [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) for assistance.

Thanks! 💙
